---
version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:8.17.1
    hostname: elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=${ES_JAVA_OPTS:--Xms512m - Xmx512m}
      - xpack.security.enabled=false
    ports:
      - target: ${ELASTICSEARCH_PORT_RESTAPI:-9200}
        published: ${ELASTICSEARCH_PORT_RESTAPI_PUBLISHED:-9200}
        mode: host
      - target: ${ELASTICSEARCH_PORT_CLUSTER:-9300}
        published: ${ELASTICSEARCH_PORT_CLUSTER_PUBLISHED:-9300}
        mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    deploy:
      replicas: ${ELASTICSEARCH_MANAGER_REPLICAS:-1}
volumes:
  elasticsearch_data:
    name: elasticsearch_data
