---
version: "3.9"
services:
  postgres:
    image: postgres:${POSTGRES_IMAGE_TAG:-13}
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-default}
    ports:
      - target: ${POSTGRES_PORT:-5432}
        published: ${POSTGRES_PORT_PUBLISHED:-5432}
        mode: host
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint/init-multiple-dbs.sql:/docker-entrypoint-initdb.d/init-multiple-dbs.sql
    deploy:
      replicas: ${POSTGRES_MANAGER_REPLICAS:-1}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-default}",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
volumes:
  postgres_data:
networks:
  swarm_networks:
    name: ${NETWORKS_NAME:-swarm_networks}
    external: true
